### ISSUE TITLE
Form with valid default values does not have initial isFormOk = true

### ISSUE THREAD

**Issue by JeremyColton** [Albert-Gao/veasy#17]
Hi,

When I set my default state as follows:
`this.formSchema = {
            email: {
                isEmail: [true, 'Add Email'],
                default: 'admin@any.com'
            },
            resetCode: {
                minLength: 2,
                default: '0123456789'
            }
        };`

And my form's submit button is:
`<Button type="submit" onClick={this.tryLogin.bind(this)} disabled={!this.state.isFormOK}>Email password reset code</Button>`

I expect the submit button to be enabled and clickable.  But my VeasyForm fields' validation status is 'normal' and they both need to be 'ok' (valid).  This seems like a bug??

Only by clicking each field and causing an onBlur event to fire, causes VeasyForm's validation to run, each input field (email, resetCode) Veasy validation status is set to 'ok' and then isFormOk = true.

As a workaround, I tried triggering the blur event on each field via:
`componentDidMount() {
            document.getElementById("email").blur();
            document.getElementById("resetCode").blur();
    }`

But the blur event is not fired on the VeasyForm's fields!

Can you please help? :)

**Comment by Albert-Gao** [comment]
Hi, thanks for reporting,
looks like `veasy` will return `false` immediately when the one of the field's `status` is not `ok`.

Will fix ASAP.

Thanks !!

**Comment by Albert-Gao** [comment]
Fixed, it works now. Update from `NPM` please. :)

**Comment by JeremyColton** [comment]
Hi, thanks for the fast response! Amazing! 

I updated to the latest v. 1.4.4.  With the default values as above, my Veasy form's isFormOk i still = false

I need to click on a form field  and then away (cause an onBlur event) in order for Veasy to call its internal startValidating() method.

Can Veasy check for default values and call validate on init?

**Comment by Albert-Gao** [comment]
I see. The procedure must be ended before hitting the `checkIsFormOk()`. Will look into it. thanks. Seems I should write an integration test rather than a unit test for this case.

**Comment by Albert-Gao** [comment]
I think a proper solution would be after generating the initial state, the `status` should be default to `ok` if meets the condition.

**Comment by Albert-Gao** [comment]
@JeremyColton 
Should be fixed this time.

Now when you generate the initial state via `createInitialState()`, `isFormOK` won't set to ok, but be set related to the real schema and state.

Which means `isFormOK` will be true in your case even before the `onChange` or `onBlur` method get called, because the `createInitialState()` will be invoked.

Just update from the NPM.

**Comment by JeremyColton** [comment]
Great, that works, thank you so much!
