### ISSUE TITLE
Linux deployment of veasyform not using my custom error messages!

### ISSUE THREAD

**Issue by JeremyColton** [Albert-Gao/veasy#19]
I used your example form:
https://github.com/Albert-Gao/veasy/tree/master/example

I added a custom error message as follows:
`        this.formSchema = {
            title: { minLength: [3, 'Its too short'] },
            description: { minLength: [5, 'not good'] },
            answer: { default: "not care" }
        };`

When I run locally on my windows laptop it works great. I see the custom error message: "Its too short".
I run via npm start which runs:
webpack-dev-server --progress --colors --inline --env.dev

But when I run the production build locally:
npm run-script build which generates a /build folder and an index.bundle.js etc. via:
webpack -p --progress --env.prod

I see the default error message: "title's length should be equal or greater than 3,Its too short. Current: 1" ! It's ignored my custom error message! The error message doesn't vanish when the minLength >=5! It seems my validation is being ignored!...

But I see my new code above in the Chrome react debug console. I don't see any errors in the console tab.

My package.json is:
`{
  "name": "ui",
  "version": "1.0.0",
  "description": "UI",
  "author": "me@a.com>",
  "url": "https://me.com",
  "copyright": "Copyright 2017",
  "license": "MIT",
  "private": true,
  "homepage": ".",
  "devDependencies": {
    "babel-core": "6.26.0",
    "babel-loader": "7.1.2",
    "babel-plugin-transform-object-rest-spread": "6.26.0",
    "babel-preset-env": "1.6.0",
    "babel-preset-react": "6.24.1",
    "copy-webpack-plugin": "4.0.1",
    "css-hot-loader": "1.3.1",
    "css-loader": "0.28.7",
    "extract-text-webpack-plugin": "3.0.0",
    "file-loader": "0.11.2",
    "html-loader": "0.5.1",
    "html-webpack-plugin": "2.30.1",
    "node-sass": "4.5.3",
    "rimraf": "2.6.2",
    "sass-loader": "6.0.6",
    "source-list-map": "2.0.0",
    "style-loader": "0.18.2",
    "uglify-js": "3.1.1",
    "url-loader": "0.5.9",
    "webpack": "3.6.0",
    "webpack-dev-server": "2.8.2"
  },
  "dependencies": {
    "bootstrap": "4.0.0-beta.2",
    "chart.js": "2.7.0",
    "font-awesome": "4.7.0",
    "history": "4.7.2",
    "is-url-external": "1.0.3",
    "jquery": "3.2.1",
    "popper.js": "1.12.6",
    "react": "15.6.1",
    "react-bootstrap-table": "4.0.6",
    "react-chartjs-2": "2.6.2",
    "react-dom": "15.6.1",
    "react-router-dom": "4.2.2",
    "react-transition-group": "1.2.0",
    "reactstrap": "4.8.0",
    "simple-line-icons": "2.4.1",
    "veasy": "^1.4.5"
  },
  "scripts": {
    "dev": "webpack -d --progress --watch --profile --json > compilation-stats.json --env.dev",
    "start": "webpack-dev-server --progress --colors --inline --env.dev",
    "build": "webpack -p --progress --env.prod",
    "clean": "rimraf ./build"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 5.0.0"
  }
}
`

Have you seen similar behaviour?

**Comment by Albert-Gao** [comment]
Sorry for the bug, updated from NPM. Should be fixed now.
It caused by the uglify procedure which will change the function name that the code relies on. :(

**Comment by JeremyColton** [comment]
I took version 1.4.6 and validation NOW works with uglify! Wonderful! Thank you, thank you!
