### ISSUE TITLE
Add inter-field validation dependency

### ISSUE THREAD

**Issue by JeremyColton** [Albert-Gao/veasy#21]
Hi, is is possible that if field A value is 3 (from values 1-10), then field B must also have a non-null value?

In this way, field B's validation is dependent on a specific value for field A.

**Comment by Albert-Gao** [comment]
I know this use case, do you mean that when field B relies on field A, if the field A could pass its rule, then we check the field B validation, otherwise, we think field B is not valid as well?

Such as:

```javascript
{
   fieldA: {
        minLength: 1,
        maxLength: 3
   },
   fieldB: {
        minLength: 4,
        maxLength: 6,
        reliesOn: [ 'fieldA' ]
   },
}
```

From this schema:

- when fieldA could pass the validation, we will start to check fieldB
- when fieldA couldn't pass the validation, we won't check fieldB and will return an error message to state where you need to pass fieldB test first.

Is this design enough for your use case?

**Comment by JeremyColton** [comment]
...not quite...fieldA is a drop-down-list.  If option 3 is selected (eg "Movie Director") then a 2nd drop-down-list called fieldB becomes visible (eg "Assistant") and it cannot be null ie the user must select an option.

In summary, fieldB's validation depends on a specific value for fieldA.

**Comment by Albert-Gao** [comment]
I see. So field B relies on a new rule for field A rather than the original rule.

```javascript
{
   fieldA: {
        minLength: 1,
        maxLength: 3
   },
   fieldB: {
        minLength: 4,
        maxLength: 6,
        reliesOn: [ 
            fieldA: {
                equal: 'AB'  // Although we don't have an `equal` check for `string` yet
            }
        ]
   },
}
```

This is a schema that I can think of. Or you have an easier way to represent this situation?

**Comment by JeremyColton** [comment]
That schema seems like a good representation :+1:

**Comment by JeremyColton** [comment]
The 'reliesOn' isn't listed in the Rules page https://albert-gao.github.io/veasy/#/rules

It's available?

**Comment by Albert-Gao** [comment]
Yes. :)

**Comment by Albert-Gao** [comment]
Why close this? No need for this feature anymore?

**Comment by JeremyColton** [comment]
You said you provided a new release so this feature is now available?

**Comment by Albert-Gao** [comment]
Yes, after I release it. You can safely close it. :)

**Comment by JeremyColton** [comment]
Hi, there's a new release with this available?

**Comment by Albert-Gao** [comment]
Sorry for the delay. Will be there.

**Comment by JeremyColton** [comment]
Hey, I can test this any time ;)

**Comment by JeremyColton** [comment]
Just let me know when I can... ;)

**Comment by Albert-Gao** [comment]
Hi, @JeremyColton 

Just start to design the code, one question:

```javascript
{
   fieldA: {
        minLength: 1,
        maxLength: 3
   },
   fieldB: {
        minLength: 4,
        maxLength: 6,
        reliesOn: { 
            fieldA: {
                equal: 'AB'  // Although we don't have an `equal` check for `string` yet
            }
        }
   },
}
```

If fieldB relies on a different rule for fieldA, why not fieldA just decares that rule in its schema?

Could you provide me with real world use case such that I can design this for solving the problem better?

**Comment by JeremyColton** [comment]
My form has 3 fields:
1. url input
2. type drop-down 
3. regex input

If the type is "REGEX" then the user must also enter a regex expression.
This schema tries to model these dependencies:
```
{
   url: {
        isUrl: true
   },
   type: {
        enum: ['ALL', 'REGEX', 'WHITELIST'],
   },
   regex: {
        isRequired:true,
        when: { 
            type: {
                equal: 'REGEX'
            }
        }
   }
}
```

This says:

- url must be a url
- type must be one of the given enum values
-  regex validation only needs to run if the 'type' == 'REGEX'.

Ok?

**Comment by Albert-Gao** [comment]
Makes sense to me.
But even reliesOn won't support that match. Need to have another rule like `mustMatch`

**Comment by Albert-Gao** [comment]
Will implement these 2 :)

**Comment by JeremyColton** [comment]
A)
test:'must-match' is the rule (so you don't need another 'mustMatch' rule). The framework then knows that the 2 field's values must match. The 'password' field has normal validation rules eg 'minLength', 'maxLength' etc. to describe what a valid password is.

B)
test: 'value' says what value the 'type' field must be for 'regex' validation to run.

ok?

**Comment by Albert-Gao** [comment]
I see. from the outside scope. seems good. Although I don't like to use test for representing regx. but consider the language API, js programmers could understand it easily.

**Comment by JeremyColton** [comment]
So, all good?

**Comment by Albert-Gao** [comment]
Yeah, all good. :) Implementing

**Comment by Albert-Gao** [comment]
So, 2 news. All tests are passing. Seems works now. But I will add more tests.
Another is that, no `test`, you just use the original `matchRegex` rule, and when you add this rule under `reliesOn`, `veasy` will match against the target field, because all rules under this will match against target field.

**Comment by JeremyColton** [comment]
Great! Please can you provide a sample json schema to clarify?

**Comment by Albert-Gao** [comment]
```json
{
   fieldA: {
        minLength: 1,
        maxLength: 3
   },
   fieldB: {
        minLength: 4,
        maxLength: 6,
        reliesOn: { 
            fieldA: {
                     // here, you can use all `veasy` rules to validate against fieldA again, if it fails, fieldB will be failed, but won't affect the fieldA of course
            }
        }
   },
}
```

**Comment by Albert-Gao** [comment]
Will be published soon I think :D

**Comment by Albert-Gao** [comment]
You can update to `1.6.0` :) Enjoy :)

**Comment by JeremyColton** [comment]
Thanks.

I have a schema where `regex `is ONLY required if `type` (a dropdown list that always has a default value so I use Veasy `collectValues`) = 'REG EX'.  I tried:

```
this.formSchema = {
            regex: {
                isRequired: true,
                reliesOn: {
                    type: {
                        startWith: 'REG'
                    }
                }
            },
            collectValues: {
                type: 'type'
            }
        };
```

This fails.  What's the correct schema?

**Comment by Albert-Gao** [comment]
As you are using collecting values. I suppose this field is not included in the schema. 

So, if you give this field a property named `value` like the one you get from general beast field.

Then it should works.

Because when veasy tries to validate this field. It expects it to follow the convention.

**Comment by Albert-Gao** [comment]
But maybe veasy could be smarter by looking at the collectValues field as a backup.

**Comment by JeremyColton** [comment]
My dropdownlist doesn't need validation since it always has a default value (the first item in the list).  So if Veasy could check collectValues that would be awesome!

**Comment by Albert-Gao** [comment]
Yes. I understand. No need to validate it.

But it doesn't mean you can't bind the value to `type.value` instead of `type`. And it's not for validation.

Before the support is landing. This could be a workaround.

I will add the support today later in the night.

**Comment by JeremyColton** [comment]
Ah ok, to bind the dropdown's value to type.value instead of type. Ok :)

**Comment by Albert-Gao** [comment]
Seems we need a new rule named onlyWhen........

**Comment by Albert-Gao** [comment]
Update to 1.6.1 please, the collectValues should be used as a backup when `field.value` is not found in the state.

**Comment by JeremyColton** [comment]
Ok.

Can the existing 'reliesOn' syntax be cleverly used to provide the functionality provided by the potential 'onlyWhen' syntax?

**Comment by JeremyColton** [comment]
Raise a new issue?

**Comment by Albert-Gao** [comment]
Yeah. a new ticket would be thankful.

It can't be compatible.  Otherwise, need to change the existing behaviour of `isRequired`
`onlyWhen` should be the first rule that veasy checks.
