### ISSUE TITLE
How to reset the form?

### ISSUE THREAD

**Issue by JeremyColton** [Albert-Gao/veasy#22]
How do I easily reset all Veasy fields which will also remove all validation messages? I don't see an API for this...

**Comment by Albert-Gao** [comment]
Yes, there is one. But maybe the doc made it hard to find. :)

https://albert-gao.github.io/veasy/#/faq?id=what-about-the-reset-button

**Comment by JeremyColton** [comment]
I tried this and it didn't do anything. Is it calling an API that I can programmatically call?

**Comment by Albert-Gao** [comment]
```javascript
const { update, schema, allState } = this.props;
update(lib.resetForm(schema, allState));
```

It invokes an internal function named `resetForm`, and give it `schema` and `allState`.

I think you can't invoke the `resetForm` outside.

The `reset` feature should work.
It's as simple as:
1. inside your `<form>`, wrap all your other components in the `<VeasyForm>`
2. Then just put a normal `reset` button there.
3. Every time the user press this button, an `onReset` event will be triggered and will be bubbled up to the `<VeasyForm>` component and handled internally.

Could you re-produce that by giving some more details on your setup?

**Comment by JeremyColton** [comment]
Thanks for the detail. Much appreciated. I'll test this tomorrow. Thanks again.

**Comment by JeremyColton** [comment]
I found the bug. When the <VeasyForm> wraps a ReactStrap <Modal> the 'reset' event doesn't bubble up to the <VeasyForm>

My code:
`            <VeasyForm
                schema={this.formSchema}
                allState={this.state}
                update={this.updateState}
            >
                <Modal isOpen={this.props.addModal} toggle={this.props.toggleAddModal}
                       className={'modal-lg ' + this.props.className}>
                    <ModalHeader toggle={this.props.toggleAddModal}>New User</ModalHeader>
                    <ModalBody>


                            <TextInput
                                name="title"
                                placeholder="Put your title here  "
                            />
                            <TextInput
                                name="description"
                                placeholder="Put your desc here"
                            />

                            <SubmitButton
                                shouldDisable={!this.state.isFormOK}
                                onClick={this.updateFieldsValues}
                            />
                            <button type="reset">reset</button>
                            <p>Data to send: {JSON.stringify(this.state.fieldsValues)}</p>


                    </ModalBody>
                    <ModalFooter>
                        <Button type="submit" disabled={!this.state.isFormOK} id="addUserButtonModal" color="primary" onClick={this.postEntry.bind(this)}>Add</Button>

                    </ModalFooter>
                </Modal>
            </VeasyForm>`

When the <VeasyForm> is inside the <ModalBody> the reset button works ok:

`                <Modal isOpen={this.props.addModal} toggle={this.props.toggleAddModal}
                       className={'modal-lg ' + this.props.className}>
                    <ModalHeader toggle={this.props.toggleAddModal}>New User</ModalHeader>
                    <ModalBody>

                        <VeasyForm
                            schema={this.formSchema}
                            allState={this.state}
                            update={this.updateState}
                        >
                            <TextInput
                                name="title"
                                placeholder="Put your title here  "
                            />
                            <TextInput
                                name="description"
                                placeholder="Put your desc here"
                            />

                            <SubmitButton
                                shouldDisable={!this.state.isFormOK}
                                onClick={this.updateFieldsValues}
                            />
                            <button type="reset">reset</button>
                            <p>Data to send: {JSON.stringify(this.state.fieldsValues)}</p>
                        </VeasyForm>

                    </ModalBody>
                    <ModalFooter>
                        <Button type="submit" disabled={!this.state.isFormOK} id="addUserButtonModal" color="primary" onClick={this.postEntry.bind(this)}>Add</Button>
                        <Button type="reset" id="cancelUserButtonModal" color="secondary" onClick={this.props.toggleAddModal}>Cancel</Button>
                        <button type="reset" onClick={this.reset}>Reset</button>
                        <button type='reset'> Reset2 </button>
                    </ModalFooter>
                </Modal>`

**Comment by Albert-Gao** [comment]
Thanks for the feedback, yes, the reset button needs to be direct children.
A quick way to work around this is to wrap that reset button with another `<VeasyForm>`.

**Comment by JeremyColton** [comment]
If I have 2 `<VeasyForm>` components, how does the 2nd know it should check the state of the 1st?

**Comment by Albert-Gao** [comment]
They must share the same `state` if they are in the same component. And I think you need the support of `reliesOn` to do the job if one field relies on the other.
