### ISSUE TITLE
Adding fields that don't need validation by using default value still requires field to be non-null

### ISSUE THREAD

**Issue by JeremyColton** [Albert-Gao/veasy#25]
According to https://albert-gao.github.io/veasy/#/collect-values you recommend to add fields that don't need validation to the form's schema by providing a default value.

I used your sample app and added a 'comment' field to the form schema and a corresponding `<TextInput>` tag:

```javascript
class App extends Component {
  constructor() {
    super();
    this.formSchema = {
      title: { minLength: 3 },
      description: { minLength: 5 },
      answer: { default: "not care" },
      comment: {
          default:''
      }
    };
    const myState = { fieldsValues: "" };
    this.state = createInitialState(this.formSchema, myState);
  }

  updateFieldsValues = e => {
    e.preventDefault();
    this.updateState({
      fieldsValues: getFieldsValue(this.formSchema, this.state)
    });
  };

  updateState = state => {
    this.setState(state);
  };

  render() {
    return (
      <VeasyForm
        schema={this.formSchema}
        allState={this.state}
        update={this.updateState}
      >
        <TextInput
          name="title"
          placeholder="Put your title here  "
        />
        <TextInput
          name="description"
          placeholder="Put your desc here"
        />
        <TextInput
            name="comment"
            placeholder="enter comment"
        />
        <RadioButtons
          label="Answer"
          name="answer"
          values={["yes", "no", "not care"]}
        />
        <SubmitButton
          shouldDisable={!this.state.isFormOK}
          onClick={this.updateFieldsValues}
        />
        <button type="reset">reset</button>
        <p>Data to send: {JSON.stringify(this.state.fieldsValues)}</p>
      </VeasyForm>
    );
  }
}
```

If I don't provide a value for the 'comment' field, the submit button is not enabled! Why?

**Comment by JeremyColton** [comment]
Furthermore, if the default is non-null eg '123', Veasy doesn't recognise this.  The user must update the field in order for the field's status to be 'ok'.

**Comment by Albert-Gao** [comment]
that comment is a text input, so if you want to collect its value, you might want to use `collectValues`, if its value is stored in the state.

But it looks like a bug. I will look into this after I fix the previous one.

Thanks!

**Comment by Albert-Gao** [comment]
Furthermore, if you don't want `Veasy` to validate this, you can add this with a rule: `isRequired: false`
https://albert-gao.github.io/veasy/#/rules?id=normal-rules

I need to a FAQ to this.

**Comment by JeremyColton** [comment]
I don't want to collect the field's value, I want it to not be validated.  What do you mean by use `collectValues`? This is a public API?

The `isRequired: false` rule works! Many thanks.

**Comment by Albert-Gao** [comment]
Sorry for the not clear rule.

The [collectValues](https://albert-gao.github.io/veasy/#/collect-values?id=or-add-an-extra-fields-called-collectvalues) is for collecting values from your own state.

Let's say that you have a control which isn't included in the schema, but you want to use `Veasy`'s API: `getFieldsValue()` to handy get all values for sending. You can include them in the `collectValues` property of your schema.

**Comment by JeremyColton** [comment]
Ah ok, that feels a better solution than adding a "don't validate this field" rule.
