### ISSUE TITLE
Adding bootstrap-react Switch component inside VeasyForm causes exception "target.name and targetName are both non-existy"

### ISSUE THREAD

**Issue by JeremyColton** [Albert-Gao/veasy#26]
I added a react-bootstrap-switch inside the VeasyForm from https://www.npmjs.com/package/react-bootstrap-switch.  It's not included the form's validation schema.

Clicking on it causes the VeasyForm's helpers.js to try to validate the Switch's HTML div called "bootstrap-switch wrapper bootstrap-switch-on bootstrap-switch-animate bootstrap-switch-focused".  It has no HTML "name" attribute so this exception is thrown:

`helpers.js?097a:351 Uncaught Error: target.name and targetName are both non-existy`

How can I EXCLUDE the Switch from VeasyForm trying to validate it?

**Comment by Albert-Gao** [comment]
Looks like a bug to me. But it really shouldn't happen.
Maybe a filtering before validation could help with this.

Thanks !!!
I will try add a test case first!

**Comment by Albert-Gao** [comment]
Hi, I wrote a test case. But it won't trigger the validation.
It seems that this shouldn't happen.

The fact is only matched component(the one you added in the schema) will get the `status`, `errorText`, `value` and `onChange`

So, if you don't add them to the schema, it won't get an `onChange` as its prop from `VeasyForm`. Then it won't trigger the `onChange` event. Thus, won't trigger the validation. 

The test case is like this, notice that the `<Email>` is not included in the schema.

```javascript
describe('Test the <VeasyForm /> interaction', () => {
  let mockSchema;
  let mockComponent;
  let componentToRender;

  beforeEach(() => {
    mockSchema = {
      title: {
        minLength: 1,
        default: ''
      }
    };

    mockComponent = {
      state: {
        isFormOK: false,
        title: {
          status: 'normal',
          errorText: '',
          value: ''
        }
      },
      setState: () => {}
    };
   
    const Email = () => <input type="email" />;

    componentToRender = (
      <VeasyForm
        schema={mockSchema}
        allState={mockComponent.state}
        update={mockComponent.setState}
      >
        <div>
          <p>
            <Input name="title" />
          </p>
        </div>
        <input />
        <div>
          <Email super="ok" cool="true" />
        </div>
      </VeasyForm>
    );
  });

  test('should not validate if the event owner is not included in the schema', () => {
    // we render the component
    const wrapper = shallow(componentToRender);
   
    // we found the Email component
    const target = wrapper.find('Email').at(0);
    
    // make sure no onChange is passed
    expect(target.prop('onChange')).toBeFalsy();

    // we mock the triggerValidation method which is an internal method for validation
    const mockTrigger = jest.fn();
    wrapper.instance().triggerValidation = mockTrigger;

    // we trigger the onChange event
    target.simulate('change');

    // the mock function won't be triggered
    expect(mockTrigger.mock.calls.length).toBe(0);
  });
})
```

Can you provide a test case for re-producing this?

And, where did you get the `onChange` handler for your bootstrap react component? What does it looks like, or provide more info for fixing this? Thanks!

**Comment by JeremyColton** [comment]
With simple `<input>` there is no issue.

But I added a `<Switch>` tag to your sample app, it is also not included in the form's schema and I see the bug.

Here's the updated app.js:

(I apologise for the formatting, this is how it appears even with code quotes)

`import React, { Component } from "react";
import TextInput from "./TextInput";
import RadioButtons from "./RadioButtons";
import SubmitButton from "./SubmitButton";
import VeasyForm, { createInitialState, getFieldsValue } from "veasy";
import Switch from 'react-bootstrap-switch';

class App extends Component {
  constructor() {
    super();
    this.formSchema = {
      title: { minLength: 3},
      description: { minLength: 5 },
      answer: { default: "not care" }
    };
    const myState = { fieldsValues: "" };
    this.state = createInitialState(this.formSchema, myState);
    this.onUpdateStatusChange = this.onUpdateStatusChange.bind(this);
  }

  updateFieldsValues = e => {
    e.preventDefault();

    let body = getFieldsValue(this.formSchema, this.state);

    this.updateState({
      fieldsValues: getFieldsValue(this.formSchema, this.state)
    });
  };

  updateState = state => {
    this.setState(state);
  };

  render() {
    return (
      <VeasyForm
        schema={this.formSchema}
        allState={this.state}
        update={this.updateState}
      >

        <Switch name="status" onText="Active" onColor="success" offText="Disabled" />

        <TextInput
          name="title"
          placeholder="Put your title here  "
        />
        <TextInput
          name="description"
          placeholder="Put your desc here"
        />
        <TextInput
            name="comment"
            placeholder="enter comment"
        />
        <RadioButtons
          label="Answer"
          name="answer"
          values={["yes", "no", "not care"]}
        />
        <SubmitButton
          shouldDisable={!this.state.isFormOK}
          onClick={this.updateFieldsValues}
        />
        <button type="reset">reset</button>
        <p>Data to send: {JSON.stringify(this.state.fieldsValues)}</p>
      </VeasyForm>
    );
  }
}

export default App;
`

To recreate the bug:
1. Open the console tab in Chrome developer tools.
2. In the browser window toggle the Switch between active and disabled.
3. Click in the 'title' input field. You see the "Uncaught Error: target.name and targetName are both non-existy" bug.

Perhaps because the `<Switch>` has its own onChange handler added, this bubbles up to VeasyForm which tries to validate it?

**Comment by Albert-Gao** [comment]
seems it causes by the title field rather than the switch? can u check whether you bind the name prop inside the TextInput component plz?

**Comment by Albert-Gao** [comment]
@JeremyColton It's fixed in new release. Thanks!

**Comment by JeremyColton** [comment]
Great, it works 💯
