### ISSUE TITLE
Does Veasy support an array or collection of objects that can be added to the form?

### ISSUE THREAD

**Issue by JeremyColton** [Albert-Gao/veasy#27]
My form has:

1. Name
2. Set of Domain objects. Each object consists of:
Domain Name, Domain Type

A valid form must have at least 1 Domain object.

1. Does Veasy support a collection of objects where there must be at least 1 object added to the form?

For example

```
this.mainFormSchema = {
   name: {minLength: [2, 'min length 2']},
   domainSet: {
      minSize: 1,
      elementContent: {
          domainName: {isUrl: true},
          domainRule: {enum: ['Full', 'None', 'Half']}
      }
   }
}
```
2. Or should the Set be a second Veasy form and if so how do I initialise this 2nd form?
eg
```
this.mainFormSchema = {
   name: {minLength: [2, 'min length 2']},
}

this.domainFormSchema = {
  domainSet: {
      minSize: 1,
      elementContent: {
          domainName: {isUrl: true},
          domainRule: {enum: ['Full', 'None', 'Half']}
      }
   }
}


this.state = createInitialState(this.mainFormSchema, this.myState);
this.domainFormState = createInitialState(this.domainFormSchema, this.myState);

// I bind this in the constructor  
updateDomainFormState(state) {
     console.log("updating domain form state...");

     // the form's state is overrided completely each time! Better way to do this so Veasy knows about changes in the state?
     this.domainFormState = state;
}


<VeasyForm schema={this.mainFormSchema} allState={this.state} update={this.updateState}>
.
.
</VeasyForm>

<VeasyForm schema={this.domainFormSchema} allState={this.domainFormState} update={this.domainFormUpdateState}>
.
.
</VeasyForm>

```
Using the above code, the 2nd Veasy domainForm does not report error messages until onBlur is called on the 1st Veasy mainForm...

3. If I seperate the 2nd form into its own component then can it have the same <VeasyForm> param values as the 1st form? Or will its state then be considered part of the state of the 1st form even though it's in a separate React component?

**Comment by Albert-Gao** [comment]
Let's be more clear about this.

So, you want to validate against a set of entities, then the result should be one?

**Comment by JeremyColton** [comment]
I can use the form to add many domains. The form is valid if there's at least 1 domain.  A JSON representation would be:

```
{
   name: 'bob',
   domains: [
      {name: 'http://a.com', type: 'ALL'},
      {name: 'http://b.com', type: 'WHITE_LIST'}
   ]
}
```
I have realised that it's easier to have 2 VeasyForms:
i) contains 'name' and recevies any domain JSON from form ii)
ii) contains domain name and type. If these are valid then the user can click 'add' and the data is added to form i).

I'll update this task's title to 'How to have multiple Veasyforms play together' ?

**Comment by Albert-Gao** [comment]
What do you mean by `domain` here?

If I get it right. As you said, I think you can simply add 2 `<VeasyForms>`, and after validating that 2nd has valid input, them pass it back to form1 somehow.

But connecting these 2 forms shouldn't be coupled with validation steps.

**Comment by JeremyColton** [comment]
I have a form with inputs for a web domain's url and type. But I agree with you - use 2 forms and pass the valid value of one form to the other to send to the server.
