### ISSUE TITLE
Only validate field A if field B has value X

### ISSUE THREAD

**Issue by JeremyColton** [Albert-Gao/veasy#30]
I have a form of 2 fields:

1. url-type (field A)
2. regex (field B)

`regex` ONLY needs to be validated by Veasy if `url-type` = "REGEX". Veasy's isFormOk boolean consider's the regex field.

If `url-type` is any other value then Veasy must not include the `regex `field in the form's overall validation and regex's value will not influence the `isFormOk `boolean.

A schema could be:
```
{
   fieldA: {
        validateOnlyWhen: {
               fieldB: {
                      contains: "REGEX" <can have any existing Veasy string or int rule here>
               }
        }
   },
   fieldB: {
        minLength: 4,
        maxLength: 6
   }
}
```

Ok?

**Comment by Albert-Gao** [comment]
What about fieldA has another rule, 

```javascript
{
   fieldA: {
        onlyWhen: {
               fieldB: {
                      contains: "REGEX" <can have any existing Veasy string or int rule here>
               }
        },
        minLength: '6'
   },
   fieldB: {
        minLength: 4,
        maxLength: 6
   }
}
```

Will the `minLegth` get evaluated when that `onlyWhen.fieldB` is `failed`?  I suppose `onlyWhen` works like a top rule where any rules just depends on it. If `onlyWhen` failed, then it won't trigger all other rules, what do you think?

**Comment by JeremyColton** [comment]
If the `onlyWhen` rule returns false then don't include `fieldA `in the form's validation, so no need to run its `minLength` rule. So `fieldA` won't influence the isFormOk boolean.

On other words, fieldA's `minLength` rule is executed 'only when' fieldB's rule returns true.

Ok?

**Comment by Albert-Gao** [comment]
nod. same idea. :D

**Comment by JeremyColton** [comment]
I'm ready to test ;)

**Comment by JeremyColton** [comment]
Would it be possible for the `onlyWhen` `contains `test to include a String OR test?

Eg
`contains: "REGEX" || "ALL"`

**Comment by Albert-Gao** [comment]
`onlyWhen` will capable of using any existing rule. So you can use `matchRegex` inside `onlyWhen` which should suits your needs. :)

In your case, you want to use `reliesOn` inside `onlyWhen`, right?

**Comment by JeremyColton** [comment]
Yes - 1st exampe is simpler and easier to read :)

**Comment by Albert-Gao** [comment]
1.7.0 Updated. Enjoy :)

**Comment by JeremyColton** [comment]
Can `fieldB `be in `collectValues`?
eg
```
collectValues: {
     fieldB: 'fieldB'
}
```

**Comment by JeremyColton** [comment]
You wrote in the updated docs : "if it fails, fieldA will be `error` because it `reliesOn` fieldB"

You copied this from the 'reliesOn' comment? :)

**Comment by Albert-Gao** [comment]
Thanks for reporting this. I tried it.

When `description` is something not start with `a`, then `title` won't be validated even you give it a length one string like `a`.

And when `description` is something start with `a`, then `title` will be validated as normal.

Remember to update the veasy version.

The only problem is. When `onlyWhen` is `false`,  the submit button won't be enabled.

You need to add `isRequired: false` to this field to make this field not affect the `isFormOK` option.

**Comment by JeremyColton** [comment]
a) I wrote last week and I thought we agreed on: "If the onlyWhen rule returns false then don't include fieldAin the form's validation, so no need to run its minLength rule. So fieldA won't influence the isFormOk boolean."

b) If onlyWhen returns true, then run fieldA's validation rules.

How do I write the schema that satisfies a) and b) ?

**Comment by Albert-Gao** [comment]
Just as I said in the previous post:

```javascript
{
    fieldA: {
           isRequired: false,
           onlyWhen: {
                fieldB: { //rules }
           }
    }
}
```

**Comment by JeremyColton** [comment]
And if fieldA must be a minimum length of 3 chars if `onlyWhen` returns true:

```
{
    fieldA: {
           isRequired: false,
           minLength: 3,
           onlyWhen: {
                fieldB: { //rules }
           }
    }
}
```

Correct?

**Comment by Albert-Gao** [comment]
Yes, it can contain its own rules, only will only be triggered when `onlyWhen` returns `false`.

**Comment by JeremyColton** [comment]
Ahh ok. I've upgarded to 1.7.0.

I tested this using:
```
this.formSchema = {
            title: {
                isRequired: false,
                minLength: 3,
                onlyWhen: {
                    description: {
                        startWith: 'a'
                    }
                }

            },
            description: { minLength: 5 },
            answer: { default: "not care" }
        };
```
Test 1
1. I leave title empty.
2. I enter 'rrrrrrr' for description.
3. I can submit the form.  PASSES

Test 2
1. I leave title empty.
2. I replace 'rrrrrrr' for 'aaaaaaa' description.
3. I can submit the form. FAILS, I should have to enter a  min of 3 chars in the 'title' field.

**Comment by Albert-Gao** [comment]
I see. For case two, the form has been triggered by `description`, so the validation for `title` won't even been triggered. This is something tricky. I will add a test case first.

**Comment by JeremyColton** [comment]
This was the original idea - validate fieldA onlyWhen fieldB starts with 'a'. Veasy should cope with the user typing and deleting text in all the form's fields :) Sorry for all the extra work.

**Comment by Albert-Gao** [comment]
Update 1.7.1, it should behave as expect.

In terms of `onlyWhen`, the original behaviour runs fine. But in terms of `isFormOK`, yes, I think, we should make this happen.

But now something interesting will happen, which means, when you update the `description` field, `title` field will be affected as well. But I think this is expected. :)

**Comment by JeremyColton** [comment]
I've updated to 1.7.1, I see the same bug (test 2.) using your demo app with the schema I specify above:

```
this.formSchema = {
            title: {
                isRequired: false,
                minLength: 3,
                onlyWhen: {
                    description: {
                        startWith: 'a'
                    }
                }

            },
            description: { minLength: 5 },
            answer: { default: "not care" }
        };
```

**Comment by Albert-Gao** [comment]
No need for `isRequired` anymore with 1.7.1, because now `onlyWhen` will be triggered everytime the other fields get validated.

**Comment by JeremyColton** [comment]
Using:

```
this.formSchema = {
            title: {
                isRequired: false,
                minLength: 3,
                onlyWhen: {
                    description: {
                        startWith: 'a'
                    }
                }

            },
            description: { minLength: 5 },
            answer: { default: "not care" }
        };
```

- I ran the following tests:

A) App loads in browser
1. Enter 5 letters in the 'description' field starting with 'r'.
2. Can submit the form without entering a 'title' value.
PASSED

B) Re-use the form
1. Enter 5 letters in the 'description' field starting with 'a'
2. Cannot submit the form - PASSED
3. Enter a title value
4. Can submit the form - PASSED

C) Change description to start with 'r'
1. Can submit the form - PASSED
2. empty title field
3. title field's validation message is displayed - FAIL
4. cannot submit the form - FAIL
- since description doesn't start with 'a', then the title field's value should not be validated!
